version: 2.1

executors:
  kb-default-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/khams-byout

jobs:
  build:
    executor: kb-default-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: 
            - build
            - node_modules
  
  deploy:
    executor: kb-default-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build 